#!/bin/sh
# Copyright 2026 The agentctl Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Converts snapshot files from the reference checkout into golden files.
#
# Each snapshot carries a metadata header: the first `---` line through the
# next `---` line. The header length varies, so the second delimiter is
# located per file. Everything after it is the oracle body and is written
# unmodified (same bytes, same final-newline state) to
# testdata/golden/<name>.golden, where <name> is the snapshot basename with
# its crate prefix and extension removed. A mapping table is printed and
# also written to testdata/golden/MAPPING.md. Re-running overwrites both.
#
# Usage: scripts/strip-insta.sh [reference-checkout-path]

set -eu

ref="${1:-/Users/zchee/rust/src/github.com/zchee/agctl}"
repo="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
out="$repo/testdata/golden"
mapping="$out/MAPPING.md"
expected=14

if [ ! -d "$ref" ]; then
	echo "strip-insta: reference checkout not found: $ref" >&2
	exit 1
fi

mkdir -p "$out"

{
	echo "# Golden file provenance"
	echo
	echo "Generated by scripts/strip-insta.sh. Do not edit the golden files"
	echo "by hand: re-run the script against the reference checkout instead."
	echo
	echo "| Snapshot (relative to the reference checkout) | Golden |"
	echo "|---|---|"
} >"$mapping"

count=0
for snap in \
	"$ref"/src/render/snapshots/*.snap \
	"$ref"/src/tui/snapshots/*.snap \
	"$ref"/src/provider/codex/snapshots/*.snap; do
	[ -f "$snap" ] || {
		echo "strip-insta: no snapshots match: $snap" >&2
		exit 1
	}

	base="${snap##*/}"
	name="${base%.snap}"
	name="${name#agctl__}"
	golden="$out/$name.golden"

	# The second `---` line closes the header; the body starts on the
	# next line. tail emits the remaining bytes untouched, so the body's
	# final-newline state survives.
	end="$(grep -n '^---$' "$snap" | sed -n '2{s/:.*//;p;}')"
	if [ -z "$end" ]; then
		echo "strip-insta: no closing header delimiter in $snap" >&2
		exit 1
	fi
	tail -n +"$((end + 1))" "$snap" >"$golden"

	rel="${snap#"$ref"/}"
	printf '| %s | testdata/golden/%s.golden |\n' "$rel" "$name" >>"$mapping"
	count=$((count + 1))
done

if [ "$count" -ne "$expected" ]; then
	echo "strip-insta: converted $count snapshots, expected $expected" >&2
	exit 1
fi

cat "$mapping"
echo "strip-insta: wrote $count golden files to $out" >&2
