// Copyright 2026 The agentctl Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fault_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"maps"
	"strings"
	"testing"

	gocmp "github.com/google/go-cmp/cmp"
)

func TestFaultForwardingBoundaries(t *testing.T) {
	imports := loadFaultFixtureImports(t)
	tests := map[string]struct {
		path       string
		source     string
		want       int
		diagnostic string
	}{
		"violation: generated header does not exempt names": {
			path: "internal/commands/generated_fixture.go",
			source: `// Code generated by x. DO NOT EDIT.

package commands; func probe() {
	point := "hidden"; fault.Active().Is(point)
}`,
			want:       1,
			diagnostic: "fault name must reference a tagged fault constant, got point",
		},
		"control: unrelated function": {
			path: "internal/commands/fixture.go",
			source: `package commands; func Is(s string) bool { return s != "" }; func probe() {
				Is("not_an_injection")
			}`,
		},
		"control: same named helper in another package": {
			path: "internal/commands/fixture.go",
			source: `package commands; func abortRefreshFault(s string) bool { return s != "" }; func probe() {
				abortRefreshFault("not_an_injection")
			}`,
		},
		"violation: new fault package files checked": {
			path: "internal/runtime/fault/new_fixture_test.go",
			source: `package fault; func probe(name string) {
				active.Is(name)
			}`,
			want:       1,
			diagnostic: "fault name must reference a tagged fault constant, got name",
		},
		"control: existing seam file exempt": {
			path: "internal/runtime/fault/fault_testing_test.go",
			source: `package fault; func probe(name string) {
				active.Is(name); check := active.Is; check("hidden")
			}`,
		},
		"control: unrelated method": {
			path: "internal/commands/fixture.go",
			source: `package commands; type predicate struct{}; func (p predicate) Is(name string) bool { return false }; func probe() {
				var p predicate; check := p.Is; check("hidden")
			}`,
		},
		"control: writer forwarding": {
			path: "internal/secret/secret_file.go",
			source: `package secret; func (f *SecretFile) WriteWithFaults() {
				active.PausePoint(names.BeforeRename); active.Is(names.RenameFail)
			}`,
		},
		"violation: new writer expression": {
			path: "internal/secret/secret_file.go",
			source: `package secret; func (f *SecretFile) WriteWithFaults() {
				point := "hidden"; active.Is(point)
			}`,
			want:       1,
			diagnostic: "fault name must reference a tagged fault constant, got point",
		},
		"violation: same expression in another function": {
			path: "internal/secret/secret_file.go",
			source: `package secret; func anotherWriter() {
				active.Is(names.RenameFail)
			}`,
			want:       1,
			diagnostic: "fault name must reference a tagged fault constant, got names.RenameFail",
		},
		"control: abort helper forwarding": {
			path: "internal/provider/codex/refresh_fault_testing.go",
			source: `package codex; func abortRefreshFault(name string) {
				active.Is(name)
			}`,
		},
		"violation: new abort helper expression": {
			path: "internal/provider/codex/refresh_fault_testing.go",
			source: `package codex; func abortRefreshFault(name string) {
				active.Is(name + "_hidden")
			}`,
			want:       1,
			diagnostic: `fault name must reference a tagged fault constant, got name + "_hidden"`,
		},
		"control: lock helper forwarding": {
			path: "internal/secret/claude_lock_stale.go",
			source: `package secret; func (s *Seams) fault(name string) {
				s.Fault(name)
			}`,
		},
		"violation: changed lock forwarding": {
			path: "internal/secret/claude_lock_stale.go",
			source: `package secret; func (s *Seams) fault(name string) {
				point := name; s.Fault(point)
			}`,
			want:       1,
			diagnostic: "fault name must reference a tagged fault constant, got point",
		},
	}
	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			fset := token.NewFileSet()
			pkg, body, found := strings.Cut(tt.source, ";")
			if !found {
				t.Fatal("fixture must separate package declaration with a semicolon")
			}
			file, err := parser.ParseFile(fset, tt.path, pkg+`; import "`+faultImportPath+`"; var active fault.Fault; type SecretFile struct{}; type Seams struct{Fault func(string) bool}; var names struct{BeforeRename, RenameFail string}; `+body, parser.ParseComments|parser.SkipObjectResolution)
			if err != nil {
				t.Fatal(err)
			}
			got := faultSourceViolations(fset, checkFaultFixture(t, fset, map[string]*ast.File{tt.path: file}, imports))
			t.Logf("expected violations=%d; measured=%d; diagnostics=%v", tt.want, len(got), got)
			if diff := gocmp.Diff(tt.want, len(got)); diff != "" {
				t.Errorf("violation count (-want +got):\n%s\ndiagnostics: %v", diff, got)
			}
			for _, violation := range got {
				if tt.diagnostic == "" || !strings.Contains(violation, tt.diagnostic) {
					t.Errorf("diagnostic = %q, want substring %q", violation, tt.diagnostic)
				}
			}
		})
	}
}

func TestFaultReceiverShapes(t *testing.T) {
	imports := loadFaultFixtureImports(t)
	tests := map[string]struct {
		decls      string
		other      string
		otherAlias string
		path       string
		source     string
		want       int
		alias      string
		diagnostic string
		order      []string
	}{
		"violation: dot import requires qualified names": {
			alias: ".", source: `Active().Is("hidden")`, want: 1,
		},
		"violation: dot import": {
			alias: ".", source: `Active().Is(BeforeRename)`, want: 1,
			diagnostic: "fault name must reference a tagged fault constant, got BeforeRename",
		},
		"violation: comma-ok receive declaration": {
			source: `var ch <-chan fault.Fault; var injected, ok = <-ch; _ = ok; injected.Is("hidden")`, want: 1,
		},
		"violation: comma-ok receive assignment": {
			source: `var ch <-chan fault.Fault; injected, ok := <-ch; _ = ok; injected.Is("hidden")`, want: 1,
		},
		"violation: comma-ok map declaration": {
			source: `values := map[string]fault.Fault{}; var injected, ok = values["k"]; _ = ok; injected.Is("hidden")`, want: 1,
		},
		"violation: comma-ok map assignment": {
			source: `values := map[string]fault.Fault{}; injected, ok := values["k"]; _ = ok; injected.Is("hidden")`, want: 1,
		},
		"control: comma-ok unrelated receive": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `var ch <-chan predicate; var injected, ok = <-ch; _ = ok; injected.Is("ordinary")`,
		},
		"control: comma-ok unrelated map": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `values := map[string]predicate{}; injected, ok := values["k"]; _ = ok; injected.Is("ordinary")`,
		},
		"control: comma-ok boolean is not a receiver": {
			source: `values := map[string]fault.Fault{}; _, ok := values["k"]; _ = ok`,
		},
		"violation: cross-file method alias": {
			other: `var check = fault.Active().Is`, source: `check("hidden")`, want: 2,
			diagnostic: "fault",
			order:      []string{`got "hidden"`, "got fault.Active().Is"},
		},
		"violation: cross-file unqualified method expression": {
			other: `type wrapper struct{ fault.Fault }`, source: `wrapper.Is(wrapper{}, "hidden")`, want: 1,
		},
		"control: cross-file unqualified method expression constant": {
			other: `type wrapper struct{ fault.Fault }`, source: `wrapper.Is(wrapper{}, fault.BeforeRename)`,
		},
		"control: cross-file unrelated method expression": {
			other: `type wrapper struct{}; func (wrapper) Is(string) bool { return false }`, source: `wrapper.Is(wrapper{}, "ordinary")`,
		},
		"control: normal fault import": {
			source: `fault.Active().Is(fault.BeforeRename)`,
		},
		"control: aliased fault import": {
			alias: "injection", source: `injection.Active().Is(injection.BeforeRename)`,
		},
		"control: unrelated dot import": {
			decls: `import . "math"`, source: `_ = Pi; fault.Active().Is(fault.BeforeRename)`,
		},
		"violation: parenthesized factory receiver": {
			source: `(fault.Active()).Is("hidden")`, want: 1,
		},
		"violation: parenthesized bound receiver": {
			source: `injected := fault.Active(); (injected).Is("hidden")`, want: 1,
		},
		"control: parenthesized receiver tagged constant": {
			source: `(fault.Active()).Is(fault.BeforeRename)`,
		},
		"violation: inline function literal result": {
			source: `(func() fault.Fault { return fault.Active() })().Is("hidden")`, want: 1,
		},
		"control: generic embedded callable shadows fault": {
			decls:  `type Is[T any] func(string) bool; type wrapper struct{ fault.Fault; Is[int] }`,
			source: `var value wrapper; value.Is("ordinary")`,
		},
		"control: multi-argument embedded callable shadows fault": {
			decls:  `type Is[T, U any] func(string) bool; type wrapper struct{ fault.Fault; Is[int, string] }`,
			source: `var value wrapper; value.Is("ordinary")`,
		},
		"violation: explicit generic embedded field": {
			decls:  `type inner[T any] struct{ fault.Fault }; type outer struct{ inner[int] }`,
			source: `var value outer; value.inner.Is("hidden")`, want: 1,
		},
		"violation: explicit multi-argument embedded field": {
			decls:  `type inner[T, U any] struct{ fault.Fault }; type outer struct{ inner[int, string] }`,
			source: `var value outer; value.inner.Is("hidden")`, want: 1,
		},
		"violation: explicit pointer generic embedded field": {
			decls:  `type inner[T any] struct{ fault.Fault }; type outer struct{ *inner[int] }`,
			source: `var value outer; value.inner.Is("hidden")`, want: 1,
		},
		"violation: interface tuple declaration result": {
			decls:  `func pair() (fault.Fault, fault.Fault) { return fault.Active(), fault.Active() }`,
			source: `var _, injected interface{ Is(string) bool } = pair(); injected.Is("hidden")`, want: 1,
		},
		"violation: interface grouped tuple declaration result": {
			decls:  `func pair() (a, b fault.Fault) { return fault.Active(), fault.Active() }`,
			source: `var _, injected interface{ Is(string) bool } = pair(); injected.Is("hidden")`, want: 1,
		},
		"control: interface tuple second result is unrelated": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; func pair() (fault.Fault, predicate) { return fault.Active(), predicate{} }`,
			source: `var _, injected interface{ Is(string) bool } = pair(); injected.Is("ordinary")`,
		},
		"violation: channel receive receiver": {
			decls: `func invoke(ch <-chan fault.Fault) { (<-ch).Is("hidden") }`, want: 1,
		},
		"violation: named channel receive receiver": {
			decls:  `type carriers <-chan fault.Fault`,
			source: `var ch carriers; (<-ch).Is("hidden")`, want: 1,
		},
		"control: unrelated channel receive receiver": {
			decls: `type predicate struct{}; func (predicate) Is(string) bool { return false }; func invoke(ch <-chan predicate) { (<-ch).Is("ordinary") }`,
		},
		"violation: instantiated promoted method expression": {
			decls:  `type wrapper[T any] struct{ fault.Fault }`,
			source: `wrapper[int].Is(wrapper[int]{}, "hidden")`, want: 1,
		},
		"violation: multi-argument instantiated promoted method expression": {
			decls:  `type wrapper[T, U any] struct{ fault.Fault }`,
			source: `wrapper[int, string].Is(wrapper[int, string]{}, "hidden")`, want: 1,
		},
		"violation: pointer instantiated promoted method expression": {
			decls:  `type wrapper[T any] struct{ fault.Fault }`,
			source: `(*wrapper[int]).Is(&wrapper[int]{}, "hidden")`, want: 1,
		},
		"control: instantiated promoted method expression constant": {
			decls:  `type wrapper[T any] struct{ fault.Fault }`,
			source: `wrapper[int].Is(wrapper[int]{}, fault.BeforeRename)`,
		},
		"control: instantiated own method shadows promoted expression": {
			decls:  `type wrapper[T any] struct{ fault.Fault }; func (wrapper[T]) Is(string) bool { return false }`,
			source: `wrapper[int].Is(wrapper[int]{}, "ordinary")`,
		},
		"control: indexed variable shadows generic type": {
			decls:  `type wrapper[T any] struct{ fault.Fault }; type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `wrapper := []predicate{{}}; wrapper[0].Is("ordinary")`,
		},
		"control: instantiated function returns unrelated receiver": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; func factory[T any]() predicate { return predicate{} }`,
			source: `factory[int]().Is("ordinary")`,
		},
		"violation: instantiated generic embedded receiver": {
			decls:  `type wrapper[T any] struct{ fault.Fault }`,
			source: `var injected wrapper[int]; injected.Is("hidden")`, want: 1,
		},
		"violation: instantiated generic composite receiver": {
			decls:  `type wrapper[T any] struct{ fault.Fault }`,
			source: `wrapper[int]{}.Is("hidden")`, want: 1,
		},
		"violation: multi-argument generic embedded receiver": {
			decls:  `type wrapper[T, U any] struct{ fault.Fault }`,
			source: `var injected wrapper[int, string]; injected.Is("hidden")`, want: 1,
		},
		"violation: multi-argument generic composite receiver": {
			decls:  `type wrapper[T, U any] struct{ fault.Fault }`,
			source: `wrapper[int, string]{}.Is("hidden")`, want: 1,
		},
		"violation: generic embedding through declaring file alias": {
			otherAlias: "injection", other: `type wrapper[T any] struct{ injection.Fault }`,
			source: `wrapper[int]{}.Is("hidden")`, want: 1,
		},
		"control: unrelated generic embedded receiver": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; type wrapper[T any] struct{ predicate }`,
			source: `var injected wrapper[int]; injected.Is("ordinary")`,
		},
		"control: generic method shadows embedded fault": {
			decls:  `type wrapper[T any] struct{ fault.Fault }; func (wrapper[T]) Is(string) bool { return false }`,
			source: `var injected wrapper[int]; injected.Is("ordinary")`,
		},
		"violation: stored function literal result": {
			source: `makeFault := func() fault.Fault { return fault.Active() }; makeFault().Is("hidden")`, want: 1,
		},
		"violation: typed callable parameter result": {
			decls: `func invoke(factory func() fault.Fault) { factory().Is("hidden") }`, want: 1,
		},
		"violation: declared function value result": {
			source: `var factory func() fault.Fault; factory().Is("hidden")`, want: 1,
		},
		"control: unrelated callable result": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; func invoke(factory func() predicate) { factory().Is("ordinary") }`,
			source: `factory := func() predicate { return predicate{} }; factory().Is("ordinary")`,
		},
		"violation: nonfirst tuple assignment result": {
			decls:  `func pair() (int, fault.Fault) { return 0, fault.Active() }`,
			source: `_, injected := pair(); injected.Is("hidden")`, want: 1,
		},
		"violation: nonfirst tuple declaration result": {
			decls:  `func pair() (int, fault.Fault) { return 0, fault.Active() }`,
			source: `var _, injected = pair(); injected.Is("hidden")`, want: 1,
		},
		"violation: grouped tuple assignment result": {
			decls:  `func pair() (a, b int, injected fault.Fault) { return 0, 0, fault.Active() }`,
			source: `_, _, injected := pair(); injected.Is("hidden")`, want: 1,
		},
		"violation: grouped tuple declaration result": {
			decls:  `func pair() (a, b fault.Fault) { return fault.Active(), fault.Active() }`,
			source: `var _, injected = pair(); injected.Is("hidden")`, want: 1,
		},
		"control: tuple second result is unrelated": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; func pair() (fault.Fault, predicate) { return fault.Active(), predicate{} }`,
			source: `_, assigned := pair(); assigned.Is("ordinary"); var _, declared = pair(); declared.Is("ordinary")`,
		},
		"violation: ranged receive-only channel": {
			decls: `func invoke(ch <-chan fault.Fault) { for injected := range ch { injected.Is("hidden") } }`, want: 1,
		},
		"violation: ranged named channel": {
			decls:  `type carriers <-chan fault.Fault`,
			source: `var ch carriers; for injected := range ch { injected.Is("hidden") }`, want: 1,
		},
		"control: ranged unrelated channel": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; type carriers <-chan predicate`,
			source: `var ch carriers; for injected := range ch { injected.Is("ordinary") }`,
		},
		"violation: indexed slice receiver": {
			source: `values := []fault.Fault{fault.Active()}; values[0].Is("hidden")`, want: 1,
		},
		"violation: indexed map receiver": {
			source: `values := map[string]fault.Fault{"active": fault.Active()}; values["active"].Is("hidden")`, want: 1,
		},
		"violation: indexed named collection receiver": {
			decls:  `type carriers []fault.Fault`,
			source: `values := carriers{fault.Active()}; values[0].Is("hidden")`, want: 1,
		},
		"violation: value embedded receiver": {
			decls:  `type wrapper struct{ fault.Fault }`,
			source: `var value wrapper; value.Is("hidden")`, want: 1,
		},
		"violation: pointer embedded receiver": {
			decls:  `type wrapper struct{ *fault.Fault }`,
			source: `var value wrapper; value.Is("hidden")`, want: 1,
		},
		"violation: explicit embedded field receiver": {
			decls:  `type wrapper struct{ fault.Fault }`,
			source: `var value wrapper; value.Fault.Is("hidden")`, want: 1,
		},
		"violation: nested promoted receiver": {
			decls:  `type inner struct{ fault.Fault }; type outer struct{ inner }`,
			source: `var value outer; value.Is("hidden")`, want: 1,
		},
		"violation: cross-file inferred global": {
			other: `var injected = fault.Active()`, source: `injected.Is("hidden")`, want: 1,
		},
		"violation: cross-file typed global": {
			other: `var injected fault.Fault`, source: `injected.Is("hidden")`, want: 1,
		},
		"violation: local embedded type": {
			source: `type wrapper struct{ fault.Fault }; var injected wrapper; injected.Is("hidden")`, want: 1,
		},
		"control: local type shadows package embedding": {
			decls:  `type wrapper struct{ fault.Fault }`,
			source: `type wrapper struct{ Is func(string) bool }; injected := wrapper{Is: func(string) bool { return false }}; injected.Is("ordinary")`,
		},
		"violation: ranged slice value": {
			source: `for _, injected := range []fault.Fault{fault.Active()} { injected.Is("hidden") }`, want: 1,
		},
		"violation: ranged array value": {
			source: `for _, injected := range [1]fault.Fault{fault.Active()} { injected.Is("hidden") }`, want: 1,
		},
		"violation: ranged map value": {
			source: `for _, injected := range map[string]fault.Fault{"active": fault.Active()} { injected.Is("hidden") }`, want: 1,
		},
		"violation: ranged map key": {
			source: `for injected := range map[*fault.Fault]string{} { injected.Is("hidden") }`, want: 1,
		},
		"control: ranged unrelated value": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `for _, injected := range []predicate{{}} { injected.Is("ordinary") }`,
		},
		"control: ranged map key does not take value type": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `for injected := range map[predicate]fault.Fault{} { injected.Is("ordinary") }`,
		},
		"control: ranged map value does not take key type": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `for _, injected := range map[*fault.Fault]predicate{} { injected.Is("ordinary") }`,
		},
		"violation: instantiated generic result": {
			decls:  `func carrier[T any](value T) fault.Fault { return fault.Active() }`,
			source: `carrier[int](0).Is("hidden")`, want: 1,
		},
		"violation: multi-argument instantiated generic result": {
			decls:  `func carrier[T, U any](value T, other U) fault.Fault { return fault.Active() }`,
			source: `carrier[int, string](0, "value").Is("hidden")`, want: 1,
		},
		"control: unrelated instantiated generic result": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; func carrier[T any](value T) predicate { return predicate{} }`,
			source: `carrier[int](0).Is("ordinary")`,
		},
		"violation: known fault initializer of interface": {
			source: `var injected interface{ Is(string) bool } = fault.Active(); injected.Is("hidden")`, want: 1,
		},
		"control: unrelated initializer of interface": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `var injected interface{ Is(string) bool } = predicate{}; injected.Is("ordinary")`,
		},
		"control: alias method expression constant": {
			decls:  `type carrier = fault.Fault`,
			source: `carrier.Is(fault.Active(), fault.BeforeRename)`,
		},
		"violation: alias method expression name": {
			decls:  `type carrier = fault.Fault`,
			source: `carrier.Is(fault.Active(), "hidden")`, want: 1,
		},
		"control: promoted method expression constant": {
			decls:  `type wrapper struct{ fault.Fault }`,
			source: `wrapper.Is(wrapper{}, fault.BeforeRename)`,
		},
		"violation: promoted method expression name": {
			decls:  `type wrapper struct{ fault.Fault }`,
			source: `(*wrapper).Is(&wrapper{}, "hidden")`, want: 1,
		},
		"control: parameter shadows package helper": {
			path:  "internal/provider/codex/fixture.go",
			decls: `func unrelated(abortRefreshFault func(string) bool) { abortRefreshFault("ordinary") }`,
		},
		"control: uninitialized function shadows package helper": {
			path:   "internal/provider/codex/fixture.go",
			source: `var abortRefreshFault func(string) bool; abortRefreshFault("ordinary")`,
		},
		"violation: real package helper": {
			path:   "internal/provider/codex/fixture.go",
			source: `abortRefreshFault("hidden")`, want: 1,
		},
		"violation: indexed array receiver": {
			source: `values := [1]fault.Fault{fault.Active()}; values[0].Is("hidden")`, want: 1,
		},
		"control: function field shadows promoted method": {
			decls:  `type wrapper struct{ fault.Fault; Is func(string) bool }`,
			source: `var value wrapper; value.Is("ordinary")`,
		},
		"violation: recursive embedding finds shallow method": {
			decls:  `type wrapper struct{ *wrapper; fault.Fault }`,
			source: `var value wrapper; value.Is("hidden")`, want: 1,
		},
		"violation: declaring file import alias": {
			otherAlias: "injection",
			other:      `type wrapper struct{ injection.Fault }; var injected wrapper`,
			source:     `injected.Is("hidden")`, want: 1,
		},
		"control: local variable shadows cross-file fault": {
			other:  `var injected = fault.Active()`,
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }`,
			source: `injected := predicate{}; injected.Is("ordinary")`,
		},
		"control: unrelated promoted Is method": {
			decls:  `type predicate struct{}; func (predicate) Is(string) bool { return false }; type wrapper struct{ predicate }`,
			source: `var value wrapper; value.Is("hidden")`,
		},
		"control: shadowing Is method": {
			decls:  `type wrapper struct{ fault.Fault }; func (wrapper) Is(string) bool { return false }`,
			source: `var value wrapper; value.Is("hidden")`,
		},
	}
	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			fset := token.NewFileSet()
			files := make(map[string]*ast.File)
			path := tt.path
			if path == "" {
				path = "internal/commands/fixture.go"
			}
			bodies := map[string]string{path: tt.decls + "\nfunc probe() {" + tt.source + "}"}
			if tt.other != "" {
				bodies["internal/commands/globals.go"] = tt.other
			}
			if strings.HasPrefix(path, "internal/provider/codex/") {
				bodies["internal/provider/codex/refresh_fault_testing.go"] = `func abortRefreshFault(name string) { fault.Active().Is(name) }`
			}
			for path, body := range bodies {
				alias := "fault"
				if !strings.HasSuffix(path, "/globals.go") && tt.alias != "" {
					alias = tt.alias
				}
				if strings.HasSuffix(path, "/globals.go") && tt.otherAlias != "" {
					alias = tt.otherAlias
				}
				pkg := "commands"
				if strings.HasPrefix(path, "internal/provider/codex/") {
					pkg = "codex"
				}
				file, err := parser.ParseFile(fset, path, `package `+pkg+`; import `+alias+` "`+faultImportPath+`"; `+body, parser.SkipObjectResolution)
				if err != nil {
					t.Fatal(err)
				}
				files[path] = file
			}
			got := faultSourceViolations(fset, checkFaultFixture(t, fset, files, imports))
			t.Logf("expected violations=%d; measured=%d; diagnostics=%v", tt.want, len(got), got)
			if tt.order != nil {
				var order []string
				for _, diagnostic := range got {
					_, suffix, _ := strings.CutLast(diagnostic, ", ")
					order = append(order, suffix)
				}
				if diff := gocmp.Diff(tt.order, order); diff != "" {
					t.Errorf("diagnostic order (-want +got):\n%s", diff)
				}
			}
			if diff := gocmp.Diff(tt.want, len(got)); diff != "" {
				t.Errorf("violation count (-want +got):\n%s\ndiagnostics: %v", diff, got)
			}
			diagnostic := tt.diagnostic
			if diagnostic == "" {
				diagnostic = `fault name must reference a tagged fault constant, got "hidden"`
			}
			for _, violation := range got {
				if !strings.Contains(violation, diagnostic) {
					t.Errorf("unexpected diagnostic: %s", violation)
				}
			}
		})
	}
}

func TestFaultCrossPackageHelpers(t *testing.T) {
	imports := loadFaultFixtureImports(t)
	tests := map[string]struct {
		argument string
		want     []string
	}{
		"violation: helper across package test variants":        {argument: `"hidden"`, want: []string{"got name", `got "hidden"`}},
		"control: helper across package test variants constant": {argument: "fault.BeforeRename", want: []string{"got name"}},
	}
	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			fset := token.NewFileSet()
			const helperPath = "internal/commands/helper.go"
			helper, err := parser.ParseFile(fset, helperPath, `package commands; import "`+faultImportPath+`"; func Forward(name string) { fault.Active().Is(name) }`, parser.SkipObjectResolution)
			if err != nil {
				t.Fatal(err)
			}
			helperFiles := map[string]*ast.File{helperPath: helper}
			normal := checkFaultFixture(t, fset, helperFiles, imports)
			variant := checkFaultFixture(t, fset, helperFiles, imports)
			callerImports := maps.Clone(imports)
			callerImports[faultModulePath+"/internal/commands"] = normal[helperPath].pkg
			const callerPath = "internal/provider/codex/fixture.go"
			caller, err := parser.ParseFile(fset, callerPath, `package codex; import ("`+faultImportPath+`"; "`+faultModulePath+`/internal/commands"); func probe() { commands.Forward(`+tt.argument+`) }`, parser.SkipObjectResolution)
			if err != nil {
				t.Fatal(err)
			}
			callerSources := checkFaultFixture(t, fset, map[string]*ast.File{callerPath: caller}, callerImports)
			maps.Copy(variant, callerSources)
			got := faultSourceViolations(fset, variant)
			var messages []string
			for _, diagnostic := range got {
				_, suffix, _ := strings.CutLast(diagnostic, ", ")
				messages = append(messages, suffix)
			}
			t.Logf("measured violations=%d; diagnostics=%v", len(got), got)
			if diff := gocmp.Diff(tt.want, messages); diff != "" {
				t.Errorf("cross-package diagnostics (-want +got):\n%s", diff)
			}
		})
	}
}

func TestFaultStemShapes(t *testing.T) {
	tests := map[string]struct {
		stem string
		want bool
	}{
		"control: lowercase":            {stem: "fault", want: true},
		"control: underscore":           {stem: "flock_enotsup", want: true},
		"control: digits after start":   {stem: "fault2", want: true},
		"violation: empty":              {},
		"violation: uppercase":          {stem: "Fault"},
		"violation: leading digit":      {stem: "2fault"},
		"violation: leading underscore": {stem: "_fault"},
		"violation: punctuation":        {stem: "fault-name"},
		"violation: whitespace":         {stem: "fault name"},
	}
	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			if diff := gocmp.Diff(tt.want, validFaultStem(tt.stem)); diff != "" {
				t.Errorf("validFaultStem(%q) (-want +got):\n%s", tt.stem, diff)
			}
		})
	}
}
